Controllers/FasbCompareController.cs
using LNTADSpreadsheets.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace LNTADSpreadsheets.Controllers
{
    public class FasbCompareController : Controller
    {
        private readonly IWebHostEnvironment Environment;
        private readonly IConfiguration Configuration;
        private readonly AppDBContext dbContext;
        private readonly UserManager<AppUser> userManager;

        public FasbCompareController(IWebHostEnvironment environment, IConfiguration configuration, AppDBContext dbContext, UserManager<AppUser> userManager)
        {
            Environment = environment;
            Configuration = configuration;
            this.dbContext = dbContext;
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            if (HttpContext.Session.GetString("username") == null || HttpContext.Session.GetString("IsValidTwoFactorAuthentication") == null || HttpContext.Session.GetString("IsValidTwoFactorAuthentication") != "true")
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                return View(await dbContext.tReports.Where(a => a.IsDeleted == false && a.PubType == "FASB" && a.Category == "compare").OrderByDescending(a => a.DateCreated).ToListAsync());
            }
        }

        [Authorize]
        [DisableRequestSizeLimit, RequestFormLimits(MultipartBodyLengthLimit = int.MaxValue,
         ValueLengthLimit = int.MaxValue)]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> Upload(List<IFormFile> postedFiles)
        {
            string user = userManager.GetUserAsync(User).Result.FirstName + " " + userManager.GetUserAsync(User).Result.LastName;

            if (postedFiles.Count == 0)
            {
                ModelState.AddModelError(string.Empty, "No files selected.");
                ViewBag.UploadMsg = "Error/s encountered.";
                return View("Index", await dbContext.tArchives.Where(a => a.IsDeleted == "0" && !a.FileName.Contains("_16")).OrderByDescending(a => a.DateCreated).ToListAsync());
            }

            List<string> errorList = new();
            DateTime fileDate = DateTime.Now;
            // Define an array of allowed file extensions
            string[] allowedExtensions = { ".xls", ".xlsx"};
            string[] category = { "compare", "complete" };

            foreach (IFormFile postedFile in postedFiles)
            {
                string fileName = postedFile.FileName;
                if (postedFile.Length == 0)
                {
                    errorList.Add($"{fileName} - File is empty.");
                    continue;
                }

                string fileExtension = Path.GetExtension(fileName).ToLowerInvariant();

                if (!Array.Exists(allowedExtensions, ext => ext.Equals(fileExtension, StringComparison.OrdinalIgnoreCase)))
                {
                    errorList.Add($"{fileName} - File type should be 'xls, xlsx and html'");
                    continue;
                }

                if (fileName.Contains("FASB", StringComparison.OrdinalIgnoreCase) == false)
                {
                    errorList.Add($"{fileName} - File doesn't match required filenaming.");
                    continue;
                }

                //if (!category.All(word => fileName.Contains(word, StringComparison.OrdinalIgnoreCase)))
                //{
                //    errorList.Add($"{fileName} - File doesn't match required filenaming.");
                //    continue;
                //}

                Console.WriteLine(fileName);
                var doesExist = dbContext.tReports.Where(a => a.FileName == fileName && a.IsDeleted == false).Select(a => a.FileName).FirstOrDefault();
                if (doesExist != null)
                {
                    if (doesExist.Any())
                    {
                        errorList.Add($"{fileName} - File alread archived.");
                        continue;
                    }
                }

            }

            if (errorList.Count != 0)
            {
                ModelState.AddModelError(string.Empty, "File upload was terminated. No files were uploaded.");
                foreach (string errorMsg in errorList)
                {
                    ModelState.AddModelError(string.Empty, errorMsg);
                }

                ViewBag.UploadMsg = "Error/s encountered.";

                return View("Index", await dbContext.tReports.Where(a => a.IsDeleted == false && a.PubType == "FASB" && a.Category == "compare").OrderByDescending(a => a.DateCreated).ToListAsync());
            }

            List<string> lstUploadedFiles = new();

            foreach (var formFile in postedFiles)
            {
                string fileName = formFile.FileName;

                string dirArchive = Configuration.GetSection("DirectorySettings")["ArchivesDirectory"];
                string filePathArchive = Path.Combine(Environment.WebRootPath, dirArchive);
                string pubType = (fileName.Contains("FASB", StringComparison.OrdinalIgnoreCase)) ? "FASB" : "GASB";
                string _category = (fileName.Contains("compare", StringComparison.OrdinalIgnoreCase)) ? "compare" : "complete";

                using (var stream = new FileStream(Path.Combine(filePathArchive, fileName), FileMode.Create))
                {
                    //upload
                    await formFile.CopyToAsync(stream);
                    lstUploadedFiles.Add(fileName);

                    //update database
                    double size = (double)formFile.Length / 1000;
                    var archiveModel = new ReportModel();
                    archiveModel.FileName = fileName;
                    archiveModel.Size = size.ToString();
                    archiveModel.DateCreated = fileDate;
                    archiveModel.CreatedBy = user;
                    archiveModel.IsDeleted = false;
                    archiveModel.PubType = pubType;
                    archiveModel.Category = _category;

                    await dbContext.tReports.AddAsync(archiveModel);
                    await dbContext.SaveChangesAsync();
                }
            }

            ViewBag.UploadMsg += string.Format("File upload was <b>successful</b>.<br />");
            foreach (string fileName in lstUploadedFiles)
            {
                ViewBag.UploadMsg += string.Format("<b>{0}</b> was uploaded.<br />", fileName);
            }


            return View("Index", await dbContext.tReports.Where(a => a.IsDeleted == false && a.PubType == "FASB" && a.Category == "compare").OrderByDescending(a => a.DateCreated).ToListAsync());
        }

        public IActionResult Download(string FileName)
        {
            string fileDir = Configuration.GetSection("DirectorySettings")["ArchivesDirectory"];
            string filePath = Path.Combine(Environment.WebRootPath, fileDir, FileName);

            return PhysicalFile(filePath, MimeTypes.GetMimeType(filePath), FileName);
        }

        public IActionResult Delete(string FileName, string view)
        {
            string fileDir = Configuration.GetSection("DirectorySettings")["ArchivesDirectory"];
            string filePath = Path.Combine(Environment.WebRootPath, fileDir, FileName);

            System.IO.File.Delete(filePath);
            dbContext.tReports.Where(a => a.FileName == FileName).FirstOrDefault().IsDeleted = false;
            dbContext.SaveChanges();

            ViewBag.Status = $"{FileName} was deleted successsfully.";

            return View("Index", dbContext.tReports.Where(a => a.IsDeleted == false).OrderByDescending(a => a.DateCreated).ToList());

        }
    }
}

Views/FasbCompare/Index.cshtml
@model IEnumerable<LNTADSpreadsheets.Models.ReportModel>

@{
    ViewData["Title"] = "FASB Report Spreadsheets";
}


<style>
    #submitButton {
        background-color: #e8171f;
        color: #fff;
    }

    .submit-progress {
        position: fixed;
        top: 50%;
        left: 50%;
        height: 6em;
        padding-top: 1.75em;
        width: 20em;
        margin-left: -10em;
        padding-left: 1em;
        background-color: black;
        color: white;
        text-align: center;
        -webkit-border-radius: 0.4em;
        -moz-border-radius: 0.4em;
        border-radius: 0.4em;
        box-shadow: 0.4em 0.4em rgba(0,0,0,0.6);
        -webkit-box-shadow: 0.4em 0.4em rgba(0,0,0,0.6);
        -moz-box-shadow: 0.4em 0.4em rgba(0,0,0,0.6);
        z-index: 9;
    }

        .submit-progress i {
            margin-right: 0.5em;
        }

    .modal-body {
        padding: 2rem;
        font-size: 16px;
    }

    .modal-header {
        display: initial;
        font-size: 16px;
    }

    .tCenter {
        text-align: center;
    }

    #uploadBtn, #archiveBtn {
        background-color: #e8171f;
        color: #fff;
        width: auto;
        float: right;
    }

    #uploadBtn {
        margin-left: 10px;
    }

    thead {
        cursor: pointer;
    }
</style>


<div class="modal fade" id="uploadModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close btn-info" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Info</h4>
            </div>
            <div class="modal-body" id="modal-body">
                @using (Html.BeginForm("Upload", "FasbCompare", FormMethod.Post, new { enctype = "multipart/form-data", @id = "frmTransaction" }))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-group">
                        <label class="control-label" style="width:360px;">&nbsp;Upload a File</label>
                        <br />
                        <input type="file" name="postedFiles" multiple />
                        <br />
                        <br />
                        <input type="submit" class="form-control btn" id="submitButton" style="width:115px;" value="UPLOAD" onclick="return DisplayProgressMessage();" />
                        <br />
                        <br />
                        <div id="ViewBagUpload">
                            <span style="color:green">@Html.Raw(ViewBag.UploadMsg)</span>
                        </div>
                        <br />
                        @Html.ValidationSummary(true, "", new { @class = "text-danger font-weight-bold", @style = "margin-left: 20px;" })
                    </div>
                }
                <br />
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-info" data-dismiss="modal" onclick="clearModal()">CANCEL</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal -->
</div>


<div class="form-group" id="aboveID">
    <h4 style="float: left;">FASB Compare Report</h4>
    <button type="button" class="form-control btn" id="uploadBtn" value="UPLOAD" onclick="displayUploadForm();"><i class="fas fa-upload"></i> UPLOAD</button>
</div>
<br />
<br />
<table class="table" id="dataTable-Archive">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FileName)
            </th>
            <th class="tCenter">
                @Html.DisplayNameFor(model => model.Size)
            </th>
            <th class="tCenter">
                @Html.DisplayNameFor(model => model.DateCreated)
            </th>
            <th class="tCenter">
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FileName)
                </td>
                <td class="tCenter">
                    @Html.DisplayFor(modelItem => item.Size)
                </td>
                <td class="tCenter">
                    @Html.DisplayFor(modelItem => item.DateCreated)
                </td>
                <td class="tCenter">
                    @Html.DisplayFor(modelItem => item.CreatedBy)
                </td>
                <td>
                    <a asp-action="Download" asp-controller="FasbCompare" asp-route-filename="@item.FileName"><i class="fas fa-file-download"></i></a>&nbsp;|&nbsp;
                    <a asp-action="Delete" asp-controller="FasbCompare" asp-route-filename="@item.FileName" asp-route-view="Index" onclick="return confirm('Do you wish to delete?')"><i class="fas fa-trash"></i></a>
                </td>
            </tr>
        }
    </tbody>
</table>

<div class="submit-progress" style="display: none" id="loader">
    <i class="fa fa-2x fa-spinner fa-spin"></i>
    <label>Loading. Please wait...</label>
</div>

<br />
<br />
@section Styles {
    <link href="@Url.Content("~/css/datatable.css")" rel="stylesheet" type="text/css" />
}

@section Scripts {
    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>*@
    <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
}

<script type="text/javascript">
	var status = "@ViewBag.Status";
	var uploadStatus = "@ViewBag.UploadMsg";

    $(document).ready(function () {

		if (status != "") {
            $('#myModal').modal('show');
		}

		if (uploadStatus != "") {
			displayUploadForm();
		}

		$('#dataTable-Archive').dataTable({
			"order": [],
		});
	});

	function displayUploadForm()
	{
		$('#uploadModal').modal('show');
	}

	function DisplayProgressMessage() {

		$("#submitButton").prop('disabled', true);
		$("#submitButton").attr('value', "Uploading...");
		$("#loader").show();
		var form = $("#frmTransaction");
		form.submit();
	}

	function clearModal() {
		$(".validation-summary-errors").empty();
		$("#ViewBagUpload").hide();
	}

</script>